// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextStyle } from "./TextStyle";

export type InputFieldFormat = { full_width: boolean, text_style: TextStyle, };
